### ISSUE TITLE
README.md issue

### ISSUE THREAD

**Issue by abergquist** [VFPX/VFPDosPrint#1]
Hi, Victor.

Thanks for submitting this!

In README.md, "dosprinten.chm" needs to be replaced with "dosprint_en.chm" in the following text:

`  (for more detailed help, see file dosprinten.chm included in the release package)`

since that's the actual name of the .CHM file.

TIA,

Art Bergquist
abergquist@sbcglobal.net

**Comment by vespina** [comment]
HI, Thank you for pointing me this issues.  At this time I don't know why the CHM is not working.  I will check it out as soon as I can.

**Comment by abergquist** [comment]
Hi, Victor.

I believe it was due to Windows 7; I got it working after I sent that message (should have messaged you earlier).

Thanks,

Art
