### ISSUE TITLE
Convert .FRX to .FMT?

### ISSUE THREAD

**Issue by abergquist** [VFPX/VFPDosPrint#2]
Hi, Victor.

Do you know if an existing .FRX/.FRT can be converted to an .FMT file?  I'm looking to take an existing .FRX and be able to print it on a Printek FormsPro 4503 printer but be able to specify which tractor (form) to use at runtime (0 = Front tractor, 1 = Center tractor, 2 = Rear tractor).

TIA,

Art Bergquist
abergquist@sbcglobal.net

**Comment by vespina** [comment]
Hi. Unfortunately I don't know about any utility to convert FRX to FMT files, nor how to configure the form tractor.

**Comment by abergquist** [comment]
Eventually found out from Printek Technical Support that I simply needed to install the Printek printer driver three (3) times, each time specifying a different form (tractor).  Now, we simply SET PRINTER TO the correct printer to print on a particular form/tractor.
